
    create table roles (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table user_roles (
        role_id bigint not null,
        user_id uuid not null,
        primary key (role_id, user_id)
    );

    create table users (
        enabled boolean not null,
        created_at timestamp(6) not null,
        updated_at timestamp(6) not null,
        id uuid not null,
        email varchar(255) not null unique,
        name varchar(255) not null,
        password_hash varchar(255) not null,
        primary key (id)
    );

    alter table if exists user_roles 
       add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 
       foreign key (role_id) 
       references roles;

    alter table if exists user_roles 
       add constraint FKhfh9dx7w3ubf1co1vdev94g3f 
       foreign key (user_id) 
       references users;
