server:
  port: 8761

spring:
  application:
    name: discovery-server
  cloud:
    config:
      # ESTO ES LO MÁS IMPORTANTE
      enabled: false  # Le dice: "No busques al Config Server, usa lo que tienes aquí local"

eureka:
  instance:
    hostname: localhost
  client:
    # Como él es el servidor, no necesita registrarse a sí mismo ni buscar a otros
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/