spring:
  application:
    name: security-service # IMPORTANTE: Este nombre debe ser igual al del archivo en GitHub
  cloud:
    config:
      uri: http://localhost:8888 # La dirección de Config Server
      fail-fast: true # Si no encuentra el config server, el micro no arranca (evita errores raros)

